###

POST http://localhost:8080/api/users
content-type: application/json

{
    "username": "testing",
    "password": "Testing"
}

###

GET http://localhost:8080/api/users/testing

### Update

PUT http://localhost:8080/api/users/testing
content-type: application/json

{
    "username": "plopezm",
    "password": "password"
}

###

GET http://localhost:8080/api/users/plopezm
