###

POST http://localhost:8080/api/users
content-type: application/json

{
    "username": "testing",
    "password": "Testing"
}

###

DELETE http://localhost:8080/api/users/testing

###

GET http://localhost:8080/api/users/testing
Authorization: Basic dGVzdGluZzp0ZXN0aW5n

###

GET http://localhost:8080/api/users/testing
Authorization: Bearer dGVzdGluZzp0ZXN0aW5n

###

GET http://localhost:8080/api/users/testing

### Update

PUT http://localhost:8080/api/users/testing
content-type: application/json

{
    "username": "plopezm",
    "password": "password"
}

###

GET http://localhost:8080/api/users/plopezm